### ISSUE TITLE
Confirmation Link Typo

### ISSUE THREAD

**Issue by JazzyEngineer** [pridgey/pollboy.pridgey.dev#5]
[Confirm your mail](https://jgwutnydpsecwtblogmr.supabase.co/auth/v1/verify?token=db4f636a37c0fce63a796927c05ee1dfb519167d7cc8917e5a7c6f5d&type=signup&redirect_to=https://pollboy.pridgey.dev)

**Comment by pridgey** [comment]
Fixed in the backend.
No release necessary.

![image](https://user-images.githubusercontent.com/6313650/215577696-de524c8e-db19-4644-80af-aa6be305a442.png)
