### ISSUE TITLE
Confirmation Email Link Broken

### ISSUE THREAD

**Issue by JazzyEngineer** [pridgey/pollboy.pridgey.dev#6]
[[email protected]](http://cdn-cgi/l/email-protection)

**Comment by pridgey** [comment]
Seems to be something the backend provider does naturally.

Will need to communicate with them to determine why.

**Comment by pridgey** [comment]
After working with some very helpful support people, can confirm this was an issue with their configuration with cloudflare. We were able to resolve it and now contact email should be enabled for confirmation emails
